<?php

use Illuminate\Database\Seeder;

class MenuNodesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_nodes')->delete();
        
        DB::table('menu_nodes')->insert(array (
            0 => 
            array (
                'id' => 543,
                'menu_id' => 3,
                'parent_id' => 0,
                'reference_id' => 5,
                'reference_type' => 'Modules\\Page\\Models\\Page',
                'url' => '',
                'icon_font' => '',
                'position' => 4,
                'title' => '',
                'css_class' => '',
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2016-09-27 04:40:29',
                'updated_at' => '2016-11-06 13:35:31',
            ),
            1 => 
            array (
                'id' => 544,
                'menu_id' => 3,
                'parent_id' => 0,
                'reference_id' => 1,
                'reference_type' => 'Modules\\Page\\Models\\Page',
                'url' => '',
                'icon_font' => '',
                'position' => 5,
                'title' => 'Contact',
                'css_class' => '',
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2016-09-27 04:40:29',
                'updated_at' => '2016-10-15 14:45:57',
            ),
            2 => 
            array (
                'id' => 545,
                'menu_id' => 1,
                'parent_id' => 0,
                'reference_id' => 0,
                'reference_type' => NULL,
                'url' => 'https://bms.dev',
                'icon_font' => '',
                'position' => 0,
                'title' => 'Home',
                'css_class' => '',
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2016-09-27 05:16:52',
                'updated_at' => '2020-04-07 03:16:36',
            ),
            3 => 
            array (
                'id' => 557,
                'menu_id' => 3,
                'parent_id' => 0,
                'reference_id' => 7,
                'reference_type' => 'Modules\\Plugins\\Blog\\Models\\Category',
                'url' => '',
                'icon_font' => '',
                'position' => 3,
                'title' => 'Projects',
                'css_class' => '',
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2016-09-27 05:31:43',
                'updated_at' => '2016-10-15 14:45:57',
            ),
            4 => 
            array (
                'id' => 558,
                'menu_id' => 3,
                'parent_id' => 0,
                'reference_id' => 8,
                'reference_type' => 'Modules\\Plugins\\Blog\\Models\\Category',
                'url' => '',
                'icon_font' => '',
                'position' => 2,
                'title' => 'Portfolio',
                'css_class' => '',
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2016-09-27 05:32:22',
                'updated_at' => '2016-10-15 14:45:57',
            ),
            5 => 
            array (
                'id' => 559,
                'menu_id' => 3,
                'parent_id' => 0,
                'reference_id' => 0,
                'reference_type' => NULL,
                'url' => '/downloads',
                'icon_font' => '',
                'position' => 1,
                'title' => 'Downloads',
                'css_class' => '',
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2016-09-30 17:32:32',
                'updated_at' => '2016-10-15 14:45:57',
            ),
            6 => 
            array (
                'id' => 560,
                'menu_id' => 3,
                'parent_id' => 0,
                'reference_id' => 0,
                'reference_type' => NULL,
                'url' => '/galleries',
                'icon_font' => '',
                'position' => 0,
                'title' => 'Galleries',
                'css_class' => '',
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2016-10-15 14:45:57',
                'updated_at' => '2016-10-15 14:45:57',
            ),
            7 => 
            array (
                'id' => 562,
                'menu_id' => 1,
                'parent_id' => 561,
                'reference_id' => 6,
                'reference_type' => 'Modules\\Plugins\\Blog\\Models\\Category',
                'url' => '',
                'icon_font' => '',
                'position' => 0,
                'title' => 'Events',
                'css_class' => '',
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2016-10-19 04:09:16',
                'updated_at' => '2016-10-19 04:09:16',
            ),
            8 => 
            array (
                'id' => 563,
                'menu_id' => 1,
                'parent_id' => 566,
                'reference_id' => 8,
                'reference_type' => 'Modules\\Plugins\\Blog\\Models\\Category',
                'url' => '',
                'icon_font' => '',
                'position' => 0,
                'title' => 'Portfolio',
                'css_class' => '',
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2016-10-19 04:09:16',
                'updated_at' => '2016-10-21 06:26:25',
            ),
            9 => 
            array (
                'id' => 564,
                'menu_id' => 1,
                'parent_id' => 566,
                'reference_id' => 7,
                'reference_type' => 'Modules\\Plugins\\Blog\\Models\\Category',
                'url' => '',
                'icon_font' => '',
                'position' => 1,
                'title' => 'Projects',
                'css_class' => '',
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2016-10-19 04:09:16',
                'updated_at' => '2016-10-21 06:26:25',
            ),
            10 => 
            array (
                'id' => 565,
                'menu_id' => 1,
                'parent_id' => 561,
                'reference_id' => 10,
                'reference_type' => 'Modules\\Plugins\\Blog\\Models\\Category',
                'url' => '',
                'icon_font' => '',
                'position' => 2,
                'title' => 'Resources',
                'css_class' => '',
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2016-10-19 04:09:16',
                'updated_at' => '2016-10-19 04:10:27',
            ),
            11 => 
            array (
                'id' => 566,
                'menu_id' => 1,
                'parent_id' => 0,
                'reference_id' => 0,
                'reference_type' => NULL,
                'url' => 'https://bms.dev/galleries',
                'icon_font' => '',
                'position' => 3,
                'title' => 'Galleries',
                'css_class' => '',
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2016-10-19 04:09:16',
                'updated_at' => '2020-04-07 03:16:36',
            ),
            12 => 
            array (
                'id' => 567,
                'menu_id' => 1,
                'parent_id' => 561,
                'reference_id' => 9,
                'reference_type' => 'Modules\\Plugins\\Blog\\Models\\Category',
                'url' => '',
                'icon_font' => '',
                'position' => 1,
                'title' => 'Business',
                'css_class' => '',
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2016-10-19 04:09:50',
                'updated_at' => '2016-10-19 04:09:50',
            ),
            13 => 
            array (
                'id' => 568,
                'menu_id' => 1,
                'parent_id' => 0,
                'reference_id' => 1,
                'reference_type' => 'Modules\\Page\\Models\\Page',
                'url' => '',
                'icon_font' => '',
                'position' => 4,
                'title' => 'Contact',
                'css_class' => '',
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2016-10-19 04:10:27',
                'updated_at' => '2017-12-08 14:39:34',
            ),
            14 => 
            array (
                'id' => 569,
                'menu_id' => 1,
                'parent_id' => 0,
                'reference_id' => 0,
                'reference_type' => NULL,
                'url' => 'https://codecanyon.net/item/botble-cms-php-platform-based-on-laravel-framework/16928182?ref=botble',
                'icon_font' => '',
                'position' => 1,
                'title' => 'Purchase',
                'css_class' => '',
                'target' => '_blank',
                'has_child' => 0,
                'created_at' => '2016-10-19 04:11:43',
                'updated_at' => '2016-11-18 21:26:19',
            ),
            15 => 
            array (
                'id' => 571,
                'menu_id' => 6,
                'parent_id' => 0,
                'reference_id' => 0,
                'reference_type' => NULL,
                'url' => 'https://facebook.com',
                'icon_font' => 'fa fa-facebook',
                'position' => 0,
                'title' => 'Facebook',
                'css_class' => '',
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2016-10-19 19:28:25',
                'updated_at' => '2016-10-19 19:28:25',
            ),
            16 => 
            array (
                'id' => 572,
                'menu_id' => 6,
                'parent_id' => 0,
                'reference_id' => 0,
                'reference_type' => NULL,
                'url' => 'https://twitter.com',
                'icon_font' => 'fa fa-twitter',
                'position' => 1,
                'title' => 'Twitter',
                'css_class' => '',
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2016-10-19 19:28:26',
                'updated_at' => '2016-10-19 19:28:26',
            ),
            17 => 
            array (
                'id' => 573,
                'menu_id' => 6,
                'parent_id' => 0,
                'reference_id' => 0,
                'reference_type' => NULL,
                'url' => 'https://plus.google.com',
                'icon_font' => 'fa fa-google-plus',
                'position' => 2,
                'title' => 'Google Plus',
                'css_class' => '',
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2016-10-19 19:29:24',
                'updated_at' => '2016-10-19 19:29:24',
            ),
            18 => 
            array (
                'id' => 574,
                'menu_id' => 6,
                'parent_id' => 0,
                'reference_id' => 0,
                'reference_type' => NULL,
                'url' => 'https://github.com',
                'icon_font' => 'fa fa-github',
                'position' => 3,
                'title' => 'Github',
                'css_class' => '',
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2016-10-19 19:29:24',
                'updated_at' => '2016-10-19 19:29:24',
            ),
            19 => 
            array (
                'id' => 575,
                'menu_id' => 7,
                'parent_id' => 0,
                'reference_id' => 0,
                'reference_type' => NULL,
                'url' => 'http://speckyboy.com',
                'icon_font' => '',
                'position' => 0,
                'title' => 'Speckyboy Magazine',
                'css_class' => '',
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2016-10-21 06:24:16',
                'updated_at' => '2016-10-21 06:24:16',
            ),
            20 => 
            array (
                'id' => 576,
                'menu_id' => 7,
                'parent_id' => 0,
                'reference_id' => 0,
                'reference_type' => NULL,
                'url' => 'http://tympanus.com',
                'icon_font' => '',
                'position' => 1,
                'title' => 'Tympanus-Codrops',
                'css_class' => '',
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2016-10-21 06:24:16',
                'updated_at' => '2016-10-21 06:24:16',
            ),
            21 => 
            array (
                'id' => 577,
                'menu_id' => 7,
                'parent_id' => 0,
                'reference_id' => 0,
                'reference_type' => NULL,
                'url' => 'https://kipalog.com/',
                'icon_font' => '',
                'position' => 2,
                'title' => 'Kipalog Blog',
                'css_class' => '',
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2016-10-21 06:24:16',
                'updated_at' => '2016-10-21 06:24:16',
            ),
            22 => 
            array (
                'id' => 578,
                'menu_id' => 7,
                'parent_id' => 0,
                'reference_id' => 0,
                'reference_type' => NULL,
                'url' => 'http://www.sitepoint.com',
                'icon_font' => '',
                'position' => 3,
                'title' => 'SitePoint',
                'css_class' => '',
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2016-10-21 06:24:16',
                'updated_at' => '2016-10-21 06:24:16',
            ),
            23 => 
            array (
                'id' => 579,
                'menu_id' => 7,
                'parent_id' => 0,
                'reference_id' => 0,
                'reference_type' => NULL,
                'url' => 'http://www.creativebloq.com/',
                'icon_font' => '',
                'position' => 4,
                'title' => 'CreativeBloq',
                'css_class' => '',
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2016-10-21 06:24:16',
                'updated_at' => '2016-10-21 06:24:16',
            ),
            24 => 
            array (
                'id' => 580,
                'menu_id' => 7,
                'parent_id' => 0,
                'reference_id' => 0,
                'reference_type' => NULL,
                'url' => 'http://techtalk.vn',
                'icon_font' => '',
                'position' => 5,
                'title' => 'Techtalk',
                'css_class' => '',
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2016-10-21 06:24:16',
                'updated_at' => '2016-10-21 06:24:16',
            ),
            25 => 
            array (
                'id' => 581,
                'menu_id' => 8,
                'parent_id' => 0,
                'reference_id' => 0,
                'reference_type' => NULL,
                'url' => '/',
                'icon_font' => '',
                'position' => 0,
                'title' => 'Homepage',
                'css_class' => '',
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2016-10-21 06:25:49',
                'updated_at' => '2016-10-21 06:25:49',
            ),
            26 => 
            array (
                'id' => 582,
                'menu_id' => 8,
                'parent_id' => 0,
                'reference_id' => 11,
                'reference_type' => 'Modules\\Plugins\\Blog\\Models\\Category',
                'url' => '',
                'icon_font' => '',
                'position' => 1,
                'title' => 'New & Updates',
                'css_class' => '',
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2016-10-21 06:25:49',
                'updated_at' => '2016-10-21 06:25:49',
            ),
            27 => 
            array (
                'id' => 583,
                'menu_id' => 8,
                'parent_id' => 0,
                'reference_id' => 0,
                'reference_type' => NULL,
                'url' => '/galleries',
                'icon_font' => '',
                'position' => 2,
                'title' => 'Galleries',
                'css_class' => '',
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2016-10-21 06:25:49',
                'updated_at' => '2016-10-21 06:25:49',
            ),
            28 => 
            array (
                'id' => 584,
                'menu_id' => 8,
                'parent_id' => 0,
                'reference_id' => 1,
                'reference_type' => 'Modules\\Page\\Models\\Page',
                'url' => '',
                'icon_font' => '',
                'position' => 3,
                'title' => 'Contact',
                'css_class' => '',
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2016-10-21 06:25:49',
                'updated_at' => '2016-10-21 06:25:49',
            ),
            29 => 
            array (
                'id' => 585,
                'menu_id' => 8,
                'parent_id' => 0,
                'reference_id' => 11,
                'reference_type' => 'Modules\\Plugins\\Blog\\Models\\Category',
                'url' => '',
                'icon_font' => '',
                'position' => 4,
                'title' => 'New & Updates',
                'css_class' => '',
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2016-10-21 06:25:49',
                'updated_at' => '2016-10-21 06:25:49',
            ),
            30 => 
            array (
                'id' => 586,
                'menu_id' => 8,
                'parent_id' => 0,
                'reference_id' => 7,
                'reference_type' => 'Modules\\Plugins\\Blog\\Models\\Category',
                'url' => '',
                'icon_font' => '',
                'position' => 5,
                'title' => 'Projects',
                'css_class' => '',
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2016-10-21 06:25:49',
                'updated_at' => '2016-10-21 06:25:49',
            ),
            31 => 
            array (
                'id' => 587,
                'menu_id' => 9,
                'parent_id' => 0,
                'reference_id' => 9,
                'reference_type' => 'Modules\\Plugins\\Blog\\Models\\Category',
                'url' => '',
                'icon_font' => '',
                'position' => 0,
                'title' => 'Business',
                'css_class' => '',
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2016-10-21 06:53:16',
                'updated_at' => '2016-10-21 06:53:16',
            ),
            32 => 
            array (
                'id' => 588,
                'menu_id' => 9,
                'parent_id' => 0,
                'reference_id' => 6,
                'reference_type' => 'Modules\\Plugins\\Blog\\Models\\Category',
                'url' => '',
                'icon_font' => '',
                'position' => 1,
                'title' => 'Events',
                'css_class' => '',
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2016-10-21 06:53:16',
                'updated_at' => '2016-10-21 06:53:16',
            ),
            33 => 
            array (
                'id' => 589,
                'menu_id' => 9,
                'parent_id' => 0,
                'reference_id' => 11,
                'reference_type' => 'Modules\\Plugins\\Blog\\Models\\Category',
                'url' => '',
                'icon_font' => '',
                'position' => 2,
                'title' => 'New & Updates',
                'css_class' => '',
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2016-10-21 06:53:16',
                'updated_at' => '2016-10-21 06:53:16',
            ),
            34 => 
            array (
                'id' => 590,
                'menu_id' => 9,
                'parent_id' => 0,
                'reference_id' => 8,
                'reference_type' => 'Modules\\Plugins\\Blog\\Models\\Category',
                'url' => '',
                'icon_font' => '',
                'position' => 3,
                'title' => 'Portfolio',
                'css_class' => '',
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2016-10-21 06:53:16',
                'updated_at' => '2016-10-21 06:53:16',
            ),
            35 => 
            array (
                'id' => 591,
                'menu_id' => 9,
                'parent_id' => 0,
                'reference_id' => 7,
                'reference_type' => 'Modules\\Plugins\\Blog\\Models\\Category',
                'url' => '',
                'icon_font' => '',
                'position' => 4,
                'title' => 'Projects',
                'css_class' => '',
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2016-10-21 06:53:16',
                'updated_at' => '2016-10-21 06:53:16',
            ),
            36 => 
            array (
                'id' => 592,
                'menu_id' => 9,
                'parent_id' => 0,
                'reference_id' => 10,
                'reference_type' => 'Modules\\Plugins\\Blog\\Models\\Category',
                'url' => '',
                'icon_font' => '',
                'position' => 5,
                'title' => 'Resources',
                'css_class' => '',
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2016-10-21 06:53:16',
                'updated_at' => '2016-10-21 06:53:16',
            ),
            37 => 
            array (
                'id' => 609,
                'menu_id' => 1,
                'parent_id' => 0,
                'reference_id' => 11,
                'reference_type' => 'Modules\\Plugins\\Blog\\Models\\Category',
                'url' => '',
                'icon_font' => '',
                'position' => 2,
                'title' => 'New & Updates',
                'css_class' => '',
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2017-12-08 14:39:34',
                'updated_at' => '2018-01-17 13:35:53',
            ),
            38 => 
            array (
                'id' => 610,
                'menu_id' => 1,
                'parent_id' => 0,
                'reference_id' => 9,
                'reference_type' => 'Modules\\Plugins\\Blog\\Models\\Category',
                'url' => NULL,
                'icon_font' => NULL,
                'position' => 5,
                'title' => 'Business',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 1,
                'created_at' => '2020-04-07 03:16:36',
                'updated_at' => '2020-04-07 03:16:36',
            ),
            39 => 
            array (
                'id' => 611,
                'menu_id' => 1,
                'parent_id' => 610,
                'reference_id' => 8,
                'reference_type' => 'Modules\\Plugins\\Blog\\Models\\Category',
                'url' => NULL,
                'icon_font' => NULL,
                'position' => 0,
                'title' => 'Portfolio',
                'css_class' => NULL,
                'target' => '_self',
                'has_child' => 0,
                'created_at' => '2020-04-07 03:16:36',
                'updated_at' => '2020-04-07 03:16:36',
            ),
        ));

        
    }
}